### ISSUE TITLE
Error after update to latest version

### ISSUE THREAD

**Issue by mishaaxe** [scriptPilot/app-framework#548]
After last update I got next problem. How can I decide this bug?

`ERROR in ./~/app-framework/client/app.js
Module parse failed: E:\Work\demo-chat\node_modules\babel-loader\lib\index.js!E:\Work\demo-chat\node_modules\app-framework\client\app.js Unterminated string constant (1:1)
You may need an appropriate loader to handle this file type.
SyntaxError: Unterminated string constant (1:1)
    at Parser.pp$4.raise (E:\Work\demo-chat\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp$7.readString (E:\Work\demo-chat\node_modules\webpack\node_modules\acorn\dist\acorn.js:2930:53)
    at Parser.pp$7.getTokenFromCode (E:\Work\demo-chat\node_modules\webpack\node_modules\acorn\dist\acorn.js:2724:19)
    at Parser.pp$7.readToken (E:\Work\demo-chat\node_modules\webpack\node_modules\acorn\dist\acorn.js:2477:17)
    at Parser.pp$7.nextToken (E:\Work\demo-chat\node_modules\webpack\node_modules\acorn\dist\acorn.js:2468:15)
    at Parser.pp$7.next (E:\Work\demo-chat\node_modules\webpack\node_modules\acorn\dist\acorn.js:2413:10)
    at Parser.pp$3.parseParenAndDistinguishExpression (E:\Work\demo-chat\node_modules\webpack\node_modules\acorn\dist\acorn.js:1846:12)
    at Parser.pp$3.parseExprAtom (E:\Work\demo-chat\node_modules\webpack\node_modules\acorn\dist\acorn.js:1796:19)
    at Parser.pp$3.parseExprSubscripts (E:\Work\demo-chat\node_modules\webpack\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (E:\Work\demo-chat\node_modules\webpack\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (E:\Work\demo-chat\node_modules\webpack\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (E:\Work\demo-chat\node_modules\webpack\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (E:\Work\demo-chat\node_modules\webpack\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseExpression (E:\Work\demo-chat\node_modules\webpack\node_modules\acorn\dist\acorn.js:1573:21)
    at Parser.pp$1.parseStatement (E:\Work\demo-chat\node_modules\webpack\node_modules\acorn\dist\acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (E:\Work\demo-chat\node_modules\webpack\node_modules\acorn\dist\acorn.js:638:25)`

**Comment by scriptPilot** [comment]
@mishaaxe - Please can you update with `npm update` to the latest version and check if you still have this issue? Current version is 1.6.48, you can check the installed one with `npm ls --depth 0`.

**Comment by mishaaxe** [comment]
Error same again.
I run the project as described in the instructions.

NodeJS: 7.10.0
NMP: 4.2.0
app-framework: 1.6.48
Windows10/Windows 7

**Comment by scriptPilot** [comment]
@mishaaxe - Please try again with 1.6.52, should fix your issue :-)

**Comment by mishaaxe** [comment]
Thank you, now all is well.
