### ISSUE TITLE
Error: Cordova platform installation failed for iOS. onesignal-cordova-plugin

### ISSUE THREAD

**Issue by mfkenson** [scriptPilot/app-framework#638]
Seems every time the `npm run xcode` would clean and generate a new  cordova project workspace. I would like to add cordova push notification (using OneSignal) into my project.

* I added the plugin-name in `app/config.json` but `npm run xcode` reported 

```
Error: Cordova platform installation failed for iOS.

Please open an incident on GitHub:
https://github.com/scriptPilot/app-framework/issues

**Comment by mfkenson** [comment]
```
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: de.scriptpilot.app-framework
	Name: Web2Call
iOS project created with cordova-ios@4.4.0
Installing "cordova-plugin-camera" for ios
Installing "cordova-plugin-compat" for ios
Installing "cordova-plugin-file" for ios
Plugin dependency "cordova-plugin-compat@1.1.0" already fetched, using that version.
Dependent plugin "cordova-plugin-compat" already installed on ios.
Installing "cordova-plugin-statusbar" for ios
Installing "cordova-plugin-whitelist" for ios
Installing "onesignal-cordova-plugin" for ios
Failed to install 'onesignal-cordova-plugin': Error: pod: Command failed with exit code 31
    at ChildProcess.whenDone (/Users/kenson/Develop/git-repo/web2call/node_modules/cordova/bin/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
Error: Cordova platform installation failed for iOS.

Please open an incident on GitHub:
https://github.com/scriptPilot/app-framework/issues

**Comment by mfkenson** [comment]
I finally get it working. Actually it is nothing to do with app-framework. https://documentation.onesignal.com/v3.0/docs/troubleshooting-cordova-variants

The fix is
```
sudo gem install cocoapods
pod repo update

**Comment by Shinosuki** [comment]
@mfkenson Do you mind to share how to get the onesignal-cordova-plugin works? I am able to add the plugin into my apps, but the apps won't work with my coding. 

- I coded a Onesignal class in javascript and export the class in a js file.
- I import the file into App.vue, create a new Onesignal instance and run the function in the class
- the build is success be the apps keep stuck at loading page

Do you have any advice on using the onesignal cordova plugin on this Appframework?

Thank you.
