### ISSUE TITLE
Error when updating from 1.19 to 1.20  (ansistyles)

### ISSUE THREAD

**Issue by tiptronic** [scriptPilot/app-framework#765]
If I try to update app-framework 1.19 to 1.20 I am gettng this error:
silly unbuild ansistyles@0.1.3
5743 info lifecycle ansistyles@0.1.3~preuninstall: ansistyles@0.1.3
5744 info lifecycle ansistyles@0.1.3~uninstall: ansistyles@0.1.3
5745 verbose unbuild rmStuff ansistyles@0.1.3 from /Users/andy/Sites/f7/f7test/node_modules
5747 info lifecycle ansistyles@0.1.3~postuninstall: ansistyles@0.1.3
5945 silly remove /Users/andy/Sites/f7/f7test/node_modules/npm/node_modules/ansistyles
6071 silly finalize /Users/andy/Sites/f7/f7test/node_modules/npm/node_modules/ansistyles
6073 silly saveTree │ │ │ │ ├── ansistyles@0.1.3
6077 verbose stack Error: ENOENT: no such file or directory, rename '/Users/andy/Sites/f7/f7test/node_modules/npm/node_modules/ansistyles' -> '/Users/andy/Sites/f7/f7test/node_modules/npm/node_modules/.ansistyles.DELETE'
6083 error path /Users/andy/Sites/f7/f7test/node_modules/npm/node_modules/ansistyles
6087 error enoent ENOENT: no such file or directory, rename '/Users/andy/Sites/f7/f7test/node_modules/npm/node_modules/ansistyles' -> '/Users/andy/Sites/f7/f7test/node_modules/npm/node_modules/.ansistyles.DELETE'

**Comment by tiptronic** [comment]
npm install ansistyle
npm ERR! code E404
npm ERR! 404 Not Found: ansistyle@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andy/.npm/_logs/2018-01-10T15_30_00_877Z-debug.log

**Comment by tiptronic** [comment]
When I create a new - empty - project and add app-framework, I can't install any new modules... same error

**Comment by scriptPilot** [comment]
Mhm ... for me, everything works well. What OS do you use?

**Comment by tiptronic** [comment]
I tried on 2 machines MacOS X 10.13.2 (17C88)
- node 8.9.0
- npm 5.6
I also started a fresh install (following exactly the app-framework docu).
At first npm run dev works and shows the material demo. But then I can't install any other dependencies: e.g.

```
my-app andy$ npm install --save vue-mqtt
npm WARN my-app@1.0.0 No description
npm WARN my-app@1.0.0 No repository field.
npm WARN my-app@1.0.0 No license field.

npm ERR! path /Users/andy/my-app/node_modules/npm/node_modules/ansistyles
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/andy/my-app/node_modules/npm/node_modules/ansistyles' -> '/Users/andy/my-app/node_modules/npm/node_modules/.ansistyles.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by tiptronic** [comment]
Sorry to post a longer log, but I tried something else - just to be sure:
- I created an empty project (like in the docu)
- Now I first installed vue-mqtt  (npm install vue-mqtt)  -> everything went fine
- Now I installed app-framework (npm install --save-dev app-framework) -> failed

``` 
andimac:__test andy$ npm install --save-dev app-framework

npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> fsevents@1.1.3 install /Users/andy/__test/node_modules/fsevents
> node install

[fsevents] Success: "/Users/andy/__test/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> grpc@1.7.2 install /Users/andy/__test/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

[grpc] Success: "/Users/andy/__test/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node" is installed via remote

> protobufjs@6.8.4 postinstall /Users/andy/__test/node_modules/protobufjs
> node scripts/postinstall


> @google-cloud/functions-emulator@1.0.0-alpha.29 postinstall /Users/andy/__test/node_modules/@google-cloud/functions-emulator
> node scripts/upgrade-warning


If you're upgrading @google-cloud/functions-emulator, these
are the recommended upgrade steps:

1.  Stop the currently running emulator, if any:

        functions stop

2.  Uninstall the current emulator, if any:

        npm uninstall -g @google-cloud/functions-emulator

3.  Install the new version of the emulator:

        npm install -g @google-cloud/functions-emulator

If you have trouble after upgrading, try deleting the config
directory found in:

    ~/.config/configstore/@google-cloud/functions-emulator

Then restart the emulator. You can also check for any renegade
Node.js emulator processes that may need to be killed:

    ps aux | grep node


> app-framework@1.20.0 postinstall /Users/andy/__test/node_modules/app-framework
> node scripts/postinstall

/Users/andy/__test/node_modules/app-framework/scripts/postinstall.js:128
  if (env.pkg.devDependencies['app-framework'] === '*') {
                             ^

TypeError: Cannot read property 'app-framework' of undefined
    at createSnapshot (/Users/andy/__test/node_modules/app-framework/scripts/postinstall.js:128:30)
    at completePackageJson (/Users/andy/__test/node_modules/app-framework/scripts/postinstall.js:156:3)
    at completePackageJson (/Users/andy/__test/node_modules/app-framework/scripts/postinstall.js:151:3)
    at Object.<anonymous> (/Users/andy/__test/node_modules/app-framework/scripts/postinstall.js:155:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
npm WARN __test No description
npm WARN __test No repository field.
npm WARN __test No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app-framework@1.20.0 postinstall: `node scripts/postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app-framework@1.20.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

**Comment by scriptPilot** [comment]
So, I understand you have only issues if you want to install additional modules with App Framework? Or do you have an issue in general with updating to App Framework 1.20.0 ? Just to be sure I understand well.

**Comment by tiptronic** [comment]
General issue.
Before - using 1.19 - everything was fine and I could install additional modules and everything worked fine.
When trying to update the working version to 1.20 - everything brok and npm update failed with the error above. Thus resulting in a missing/broken app-framework (it just does not install as update).

The only thing I could get to work was a clean install of app-framework but then I could not install any other module (see above).

I will investigate further tomorrow

**Comment by tiptronic** [comment]
I got it working again using 1.19 by running `npm ddp`, but now, when clicking any link, the right panel opens...

**Comment by tiptronic** [comment]
After then trying again npm update I have the same problem as before...

**Comment by tiptronic** [comment]
@scriptPilot : After some more, here's how I got it working:
- I just created an empty project and installed app-framework as dependency.
- then I ran npm ddp (where it told me it removed 243 packages, etc...)
- now I am able to add other modules and run the app (on desktop, however, on every link it also opens the right side-panel (which is a minor thing).

So obvioulsy something is going wrong @ installation. Maybe it helps if I uninstall node and npm and re-install what I need (but most likely not before the weekend)

**Comment by mdocter** [comment]
I experienced the same issue.
I got the build to work again (after the update) by deleting the `.app-framework-cache` and `app-framework` folders from the `node_modules` folder. 
After that I ran `npm install` again to restore the folders.
Now `npm run dev` works again.

**Comment by scriptPilot** [comment]
OK, but there is something wrong ... by default, after any App Framwork update, the `.app-framework-cache` folder is removed. So I expect that the "postinstall" script was not called? Or there is an issue with the access rights to that folder? Please can you investigate on that as I did not find any issue after several tests on different machines. Thanks!

**Comment by tiptronic** [comment]
hm - no problems here, since after installing and deduplicating the problem goes away... manually removing app-framework.cache didn't help in my case...

did you try on a Mac?

**Comment by tiptronic** [comment]
Btw. I did another quick test (just to be sure). I copied the whole NEW folder (containing everything) onto another machine, where the same problem occured before.
I just opened terminal and ran npm run dev - and it works fine. So the problem seems not to be related to other parts of my node/npm install. It's just a local problem... So we just need to find out the 'why'-portion of it 😉

**Comment by mdocter** [comment]
In my case it was on a Windows 10 Pro machine. 
I noticed that the `app-framework` folder (which I deleted) only contained the `.bin` folder and it's contents. So maybe something was locked by some process. 

I ran my commands from one console screen, so I didn't have some dev build running in another console window or something. 

When I created my app from scratch (this week with the previous version) `npm install` was failing. It was running out of it's memory stack or something. So maybe on my side got corrupted while trying to get it to work. I also tried Yarn etc. but that doesn't trigger the installation script, so the package.json stays empty and the source files weren't copied.

**Comment by scriptPilot** [comment]
Can you try with `npm run postinstall` after installation?

**Comment by littlegreening** [comment]
I fixed it by deleting the `package-lock.json` and ran `npm install`.

**Comment by josteph** [comment]
@littlegreening good solution!
